#!/bin/sh
if ! command -v git-lfs >/dev/null 2>&1; then
  printf >&2 "\n%s\n\n" "$(cat <<EOF
This repository is configured for Git LFS but 'git-lfs' was not found on your path.
If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').
EOF
  )"
  exit 2
fi

git lfs pre-push "$@"
